package fieldTypePostgres

import "github.com/helays/utils/db/dbFiledType"

// FieldTypeEnums 字段类型枚举 Postgres数据库的
var FieldTypeEnums = map[string]dbFiledType.FieldType{
	"int2": {
		Name:        "int2",
		FullName:    "smallint",
		Extra:       "2 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"int4": {
		Name:        "int4",
		FullName:    "integer",
		Extra:       "4 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"int8": {
		Name:        "int8",
		FullName:    "bigint",
		Extra:       "8 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"serial2": {
		Name:        "serial2",
		FullName:    "smallserial",
		Extra:       "自动递增的 2 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"serial4": {
		Name:        "serial4",
		FullName:    "serial",
		Extra:       "自动递增的 4 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"serial8": {
		Name:        "serial8",
		FullName:    "bigserial",
		Extra:       "自动递增的 8 字节整数",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"float4": {
		Name:        "float4",
		FullName:    "real",
		Extra:       "单精度浮点数 (4 字节)",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"float8": {
		Name:        "float8",
		FullName:    "double precision",
		Extra:       "双精度浮点数 (8 字节)",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"numeric": {
		Name:        "numeric",
		FullName:    "numeric",
		Extra:       "精确数值，精度和小数点位数可变",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0, // 取决于声明时指定的小数点位数
	},
	"varchar": {
		Name:        "varchar",
		FullName:    "character varying",
		Extra:       "可变长度字符串",
		DstDb:       "postgres",
		DefaultLen:  255,
		DecimalCols: 0,
	},
	"char": {
		Name:        "char",
		FullName:    "character",
		Extra:       "定长字符串",
		DstDb:       "postgres",
		DefaultLen:  1,
		DecimalCols: 0,
	},
	"text": {
		Name:        "text",
		FullName:    "text",
		Extra:       "可变长度字符串",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"bytea": {
		Name:        "bytea",
		FullName:    "bytea",
		Extra:       "二进制数据 ('字节数组')",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"timestamp without time zone": {
		Name:        "timestamp",
		FullName:    "timestamp without time zone",
		Extra:       "日期和时间，不带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"timestamp": {
		Name:        "timestamp",
		FullName:    "timestamp without time zone",
		Extra:       "日期和时间，不带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"timestamp with time zone": {
		Name:        "timestamptz",
		FullName:    "timestamp with time zone",
		Extra:       "日期和时间，带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"timestamptz": {
		Name:        "timestamptz",
		FullName:    "timestamp with time zone",
		Extra:       "日期和时间，带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"time without time zone": {
		Name:        "time",
		FullName:    "time without time zone",
		Extra:       "一天中的时间，不带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"time": {
		Name:        "time",
		FullName:    "time without time zone",
		Extra:       "一天中的时间，不带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"timetz": {
		Name:        "timetz",
		FullName:    "time with time zone",
		Extra:       "一天中的时间，带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"time with time zone": {
		Name:        "timetz",
		FullName:    "time with time zone",
		Extra:       "一天中的时间，带时区",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"date": {
		Name:        "date",
		FullName:    "date",
		Extra:       "日历日期（年-月-日）",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"interval": {
		Name:        "interval",
		FullName:    "interval",
		Extra:       "时间间隔",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"bool": {
		Name:        "bool",
		FullName:    "boolean",
		Extra:       "逻辑布尔值 (true/false)",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"uuid": {
		Name:        "uuid",
		FullName:    "uuid",
		Extra:       "通用唯一标识符",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"json": {
		Name:        "json",
		FullName:    "json",
		Extra:       "JSON 数据",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"jsonb": {
		Name:        "jsonb",
		FullName:    "jsonb",
		Extra:       "二进制 JSON 数据",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"inet": {
		Name:        "inet",
		FullName:    "inet",
		Extra:       "IPv4 或 IPv6 主机地址",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"cidr": {
		Name:        "cidr",
		FullName:    "cidr",
		Extra:       "IPv4 或 IPv6 网络地址",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"macaddr": {
		Name:        "macaddr",
		FullName:    "macaddr",
		Extra:       "MAC 地址",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"money": {
		Name:        "money",
		FullName:    "money",
		Extra:       "货币金额",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 2,
	},
	"bit": {
		Name:        "bit",
		FullName:    "bit",
		Extra:       "固定长度的位串",
		DstDb:       "postgres",
		DefaultLen:  1,
		DecimalCols: 0,
	},
	"varbit": {
		Name:        "varbit",
		FullName:    "bit varying",
		Extra:       "可变长度的位串",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"bit varying": {
		Name:        "varbit",
		FullName:    "bit varying",
		Extra:       "可变长度的位串",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"xml": {
		Name:        "xml",
		FullName:    "xml",
		Extra:       "XML 数据",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"point": {
		Name:        "point",
		FullName:    "point",
		Extra:       "几何点",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"line": {
		Name:        "line",
		FullName:    "line",
		Extra:       "无限长度线段",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"lseg": {
		Name:        "lseg",
		FullName:    "lseg",
		Extra:       "有限长度线段",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"box": {
		Name:        "box",
		FullName:    "box",
		Extra:       "二维盒子 —— 点对",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"path": {
		Name:        "path",
		FullName:    "path",
		Extra:       "闭合路径或开放路径",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"polygon": {
		Name:        "polygon",
		FullName:    "polygon",
		Extra:       "闭合几何多边形",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"circle": {
		Name:        "circle",
		FullName:    "circle",
		Extra:       "圆心和半径定义的圆",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"tsvector": {
		Name:        "tsvector",
		FullName:    "tsvector",
		Extra:       "文本搜索文档",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"tsquery": {
		Name:        "tsquery",
		FullName:    "tsquery",
		Extra:       "文本搜索查询",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"txid_snapshot": {
		Name:        "txid_snapshot",
		FullName:    "txid_snapshot",
		Extra:       "事务 ID 快照",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
	"pg_lsn": {
		Name:        "pg_lsn",
		FullName:    "pg_lsn",
		Extra:       "PostgreSQL 日志序列号",
		DstDb:       "postgres",
		DefaultLen:  0,
		DecimalCols: 0,
	},
}
