package fieldPostgres

import (
	"github.com/helays/utils/db/dbField"
)

// FieldEnums 字段类型枚举 Postgres数据库的
var FieldEnums = map[string]dbField.Field{
	"int2": {
		Name:         "int2",
		FullName:     "smallint",
		Extra:        "2 字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"int4": {
		Name:         "int4",
		FullName:     "integer",
		Extra:        "4 字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"int8": {
		Name:         "int8",
		FullName:     "bigint",
		Extra:        "8 字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"serial": {
		Name:         "serial",
		FullName:     "serial",
		Extra:        "自动递增的 4字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"serial2": {
		Name:         "serial2",
		FullName:     "smallserial",
		Extra:        "自动递增的 2字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"smallserial": {
		Name:         "serial2",
		FullName:     "smallserial",
		Extra:        "自动递增的 2字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"serial4": {
		Name:         "serial4",
		FullName:     "serial",
		Extra:        "自动递增的 4字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"serial8": {
		Name:         "serial8",
		FullName:     "bigserial",
		Extra:        "自动递增的 8字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"bigserial": {
		Name:         "serial8",
		FullName:     "bigserial",
		Extra:        "自动递增的 8字节整数",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"float4": {
		Name:         "float4",
		FullName:     "real",
		Extra:        "单精度浮点数 (4 字节)",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"float8": {
		Name:         "float8",
		FullName:     "double precision",
		Extra:        "双精度浮点数 (8 字节)",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "number",
	},
	"numeric": {
		Name:         "numeric",
		FullName:     "numeric",
		Extra:        "精确数值，精度和小数点位数可变",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   13,
		ColsReadOnly: false,
		DecimalCols:  2,
		Attribute:    "number",
	},
	"varchar": {
		Name:         "varchar",
		FullName:     "character varying",
		Extra:        "可变长度字符串",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   255,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"char": {
		Name:         "char",
		FullName:     "character",
		Extra:        "定长字符串",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   1,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"text": {
		Name:         "text",
		FullName:     "text",
		Extra:        "可变长度字符串",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"bytea": {
		Name:         "bytea",
		FullName:     "bytea",
		Extra:        "二进制数据 ('字节数组')",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "byte",
	},
	"timestamp without time zone": {
		Name:         "timestamp",
		FullName:     "timestamp without time zone",
		Extra:        "日期和时间，不带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"timestamp": {
		Name:         "timestamp",
		FullName:     "timestamp without time zone",
		Extra:        "日期和时间，不带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"timestamp with time zone": {
		Name:         "timestamptz",
		FullName:     "timestamp with time zone",
		Extra:        "日期和时间，带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"timestamptz": {
		Name:         "timestamptz",
		FullName:     "timestamp with time zone",
		Extra:        "日期和时间，带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"time without time zone": {
		Name:         "time",
		FullName:     "time without time zone",
		Extra:        "一天中的时间，不带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"time": {
		Name:         "time",
		FullName:     "time without time zone",
		Extra:        "一天中的时间，不带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"timetz": {
		Name:         "timetz",
		FullName:     "time with time zone",
		Extra:        "一天中的时间，带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"time with time zone": {
		Name:         "timetz",
		FullName:     "time with time zone",
		Extra:        "一天中的时间，带时区",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"date": {
		Name:         "date",
		FullName:     "date",
		Extra:        "日历日期（年-月-日）",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "date",
	},
	"interval": {
		Name:         "interval",
		FullName:     "interval",
		Extra:        "时间间隔",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   6,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "duration",
	},
	"bool": {
		Name:         "bool",
		FullName:     "boolean",
		Extra:        "逻辑布尔值 (true/false)",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "bool",
	},
	"uuid": {
		Name:         "uuid",
		FullName:     "uuid",
		Extra:        "通用唯一标识符",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"json": {
		Name:         "json",
		FullName:     "json",
		Extra:        "JSON 数据",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"jsonb": {
		Name:         "jsonb",
		FullName:     "jsonb",
		Extra:        "二进制 JSON 数据",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "byte",
	},
	"inet": {
		Name:         "inet",
		FullName:     "inet",
		Extra:        "IPv4 或 IPv6 主机地址",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"cidr": {
		Name:         "cidr",
		FullName:     "cidr",
		Extra:        "IPv4 或 IPv6 网络地址",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"macaddr": {
		Name:         "macaddr",
		FullName:     "macaddr",
		Extra:        "MAC 地址",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"money": {
		Name:         "money",
		FullName:     "money",
		Extra:        "货币金额",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"bit": {
		Name:         "bit",
		FullName:     "bit",
		Extra:        "固定长度的位串",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   1,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "byte",
	},
	"varbit": {
		Name:         "varbit",
		FullName:     "bit varying",
		Extra:        "可变长度的位串",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "byte",
	},
	"bit varying": {
		Name:         "varbit",
		FullName:     "bit varying",
		Extra:        "可变长度的位串",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "byte",
	},
	"xml": {
		Name:         "xml",
		FullName:     "xml",
		Extra:        "XML 数据",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"point": {
		Name:         "point",
		FullName:     "point",
		Extra:        "几何点",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"line": {
		Name:         "line",
		FullName:     "line",
		Extra:        "无限长度线段",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"lseg": {
		Name:         "lseg",
		FullName:     "lseg",
		Extra:        "有限长度线段",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"box": {
		Name:         "box",
		FullName:     "box",
		Extra:        "二维盒子 —— 点对",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"path": {
		Name:         "path",
		FullName:     "path",
		Extra:        "闭合路径或开放路径",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"polygon": {
		Name:         "polygon",
		FullName:     "polygon",
		Extra:        "闭合几何多边形",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"circle": {
		Name:         "circle",
		FullName:     "circle",
		Extra:        "圆心和半径定义的圆",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"tsvector": {
		Name:         "tsvector",
		FullName:     "tsvector",
		Extra:        "文本搜索文档",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"tsquery": {
		Name:         "tsquery",
		FullName:     "tsquery",
		Extra:        "文本搜索查询",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"txid_snapshot": {
		Name:         "txid_snapshot",
		FullName:     "txid_snapshot",
		Extra:        "事务 ID 快照",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
	"pg_lsn": {
		Name:         "pg_lsn",
		FullName:     "pg_lsn",
		Extra:        "PostgreSQL 日志序列号",
		DstDb:        "postgres",
		LenReadOnly:  true,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},

	// 这是向量数据库，需要插件的
	"vector": {
		Name:         "vector",
		FullName:     "vector",
		Extra:        "向量",
		DstDb:        "postgres",
		LenReadOnly:  false,
		DefaultLen:   0,
		ColsReadOnly: true,
		DecimalCols:  0,
		Attribute:    "string",
	},
}
